{% set name = 'R-swat' %}
{% set version = '1.4.1' %}
{% set build = '0' %}

# linux64 : r   - 3.4.3, 3.5.0, 3.6.0
#         : mro - 3.4.3, 3.5.0, 3.5.1
# osx     : r   - 3.4.3, 3.5.0, 3.5.1, 3.6.0
# win64   : r   - 3.4.3, 3.5.1, 3.6.0
#         : mro - 3.4.3, 3.5.1

{% set r_base = 'mro-base' %}
{% set r_version = '3.6.0' %}

package:
    name: {{ name|lower() }}
    version: {{ version|replace("-", "_") }}

source:
    url: https://github.com/sassoftware/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux64.tar.gz # [linux64]
    url: https://github.com/sassoftware/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux-ppc64le.tar.gz # [ppc64le]
    url: https://github.com/sassoftware/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-win64.tar.gz # [win64]
    url: https://github.com/sassoftware/{{ name }}/archive/v{{ version }}.tar.gz # [not linux64 and not win64 and not ppc64le]

build:
    number: {{ build }}
    build: False
    script: R CMD INSTALL --build --install-tests .         # [not win]
    script: "\"%R%\" CMD INSTALL --build --install-tests \"%SRC_DIR%\"" # [win]
    binary_relocation: False
    missing_dso_whitelist:
        - /lib/libpthread.so.0
        - /lib/libm.so.6
        - /lib/libc.so.6
        - /lib/libdl.so.2
        - /lib/libcrypt.so.1
        - /lib/librt.so.1
        - /lib/libresolv.so.2
        - /lib/libgcc_s.so.1
        - /lib/libstdc++.so.6
        - /lib/libXt.so.6  # begin xorgpkg.so
        - /lib/libXmu.so.6  #
        - /lib/libSM.so.6  #
        - /lib/libXext.so.6  #
        - /lib/libjpeg.so.62  #
        - /lib/libICE.so.6  #
        - /lib/libfontconfig.so.1  #
        - /lib/libXft.so.2  #
        - /lib/libpng12.so.0  #
        - /lib/libX11.so.6  # end xorgpkg.so
        - libdfschr-1.4.so
        - libdfssys-1.3.so
        - libdfsfio-1.5.so
        - libdflic-1.4.so
        - libjsig.so
        - libjvm.so
        - /lib/libgssapi_krb5.so.2
        - /lib/libkrb5.so.3
        - /lib/libuuid.so.1
        - /lib64/libnuma.so.1

requirements:
    build:
        - {{ r_base }} ={{ r_version }}
        - r-httr
        - r-jsonlite
        - r-codetools
    run:
        - {{ r_base }}
        - r-httr
        - r-jsonlite
        - libnuma      # [linux64]
        - libuuid      # [linux64]
        - krb5         # [linux64]

test:
    requires:
        - {{ r_base }} ={{ r_version }}
        - r-devtools
        - r-testthat
#       - r-xlsx
        - r-jpeg
        - r-xml2
        - zlib >=1.2.9 # [linux64]
    commands:
        - R -f "${RECIPE_DIR}/test_package.R"            # [not win]
        - "\"%R%\" -f \"%RECIPE_DIR%\\test_package.R\""  # [win]

about:
    home: https://github.com/sassoftware/R-swat
    license: Apache 2.0 + SAS Additional Functionality
    license_file: LICENSE
    summary: SAS Viya R Client
    dev_url: https://github.com/sassoftware/R-swat
